# Generated by Django 4.1.7 on 2023-06-22 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('edit_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(default='no-slug', max_length=60)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('edit_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=60)),
                ('index', models.IntegerField(default=0)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'ordering': ['-index'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('edit_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('body', models.TextField()),
                ('pub_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'DRAFT'), ('p', 'PUBLISHED')], default='d', max_length=1)),
                ('comment_status', models.CharField(choices=[('o', 'OPENED'), ('c', 'CLOSED')], default='c', max_length=1)),
                ('type', models.CharField(choices=[('a', 'EASSY'), ('p', 'PAGE')], default='a', max_length=1)),
                ('views', models.PositiveIntegerField(default=0)),
                ('article_order', models.IntegerField(default=0)),
                ('show_toc', models.BooleanField(default=False, verbose_name='Table of Contacts')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='categories')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='tags')),
            ],
            options={
                'ordering': ['-article_order', '-pub_time'],
                'get_latest_by': 'id',
            },
        ),
    ]
