# Generated by Django 4.1.7 on 2023-08-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedUserManager',
        ),
    ]
